.TH "airspy_gpio" 1 "2015.07.31" AIRSPY "User Commands"
.SH NAME
airspy_gpio \- read and write gpio pin values
.SH DESCRIPTION
The Airspy is a tiny and efficient software defined radio receiver.
.LP
This application lets the user read and write gpio pins.
.SH SYNOPSIS
.B  airspy_gpio
.SH OPTIONS
.IP "-p, --port_no <p>: set port number<p>[0,7] for subsequent read/write operations\n"
.IP "-n, --pin_no <n>: set pin number<n>[0,31] for subsequent read/write operations\n"
.IP "-r, --read: read port number/pin number value and direction specified by last -n argument, or all port/pin\n"
.IP "-w, --write <v>: write value specified by last -n argument with value<v>[0,1]\n"
.IP "[-s serial_number_64bits]: Open board with specified 64bits serial number.\n"
.SH Examples
.IP "<command> -p 0 -n 12 -r # reads from port 0 pin number 12\n"
.IP "<command> -r          # reads all pins on all ports\n"
.IP "<command> -p 0 -n 10 -w 1 # writes port 0 pin number 10 with 1 decimal\n"
.SH Hardware Info AirSpy
.IP "LED1(out): -p 0 -n 12 (0=OFF, 1=ON)\n"
.IP "Enable R820T(out): -p 1 -n 7 (0=OFF, 1=ON)\n"
.IP "Enable BiasT(out): -p 1 -n 13 (0=OFF, 1=ON)\n"
.SH SEE ALSO
Airspy web page:
.B http://airspy.com/
.LP
Other airspy programs:
.sp
airspy_info(1), airspy_si5351c(1), airspy_spiflash(1), airspy_gpio(1), airspy_gpiodir(1), airspy_lib_version(1)
.SH AUTHOR
This manual page was written by Maitland Bottoms
for the Debian project (but may be used by others).
.SH COPYRIGHT
Copyright (c) 2015 A. Maitland Bottoms <bottoms@debian.org>
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
